### ISSUE TITLE
Keyboard input broken when editing dates

### ISSUE THREAD

**Issue by optikfluffel** [Bogdanp/elm-datepicker#1]
When a date is already set, the keyboard input stops working. You can alter the date in the input field but it simply get's reset to whatever the picker sais. Wouldn't it be more usefull to update the picker if I change the date via the text input?

**Comment by Bogdanp** [comment]
Do you have some examples for the kinds of values you have tried? This should work right now for any value that `Date.fromString` can parse, assuming that date isn't disabled (i.e. for the demo the value you enter can't be a Saturday or a Sunday).

**Comment by optikfluffel** [comment]
![jun-01-2016 22-30-04](https://cloud.githubusercontent.com/assets/379915/15724679/78359d8e-2848-11e6-863c-413f2c4f1e4b.gif)

**Comment by Bogdanp** [comment]
July 16, 2016 is a Saturday :)

**Comment by optikfluffel** [comment]
Oh dammit, thanks and never mind then 😸
