### ISSUE TITLE
Allow adding more classes, for styling

### ISSUE THREAD

**Issue by Zimmi48** [Bogdanp/elm-datepicker#2]
Hello,
Your component is really great and I've added it to a form in my app.
I've started using Bootstrap CSS for styling and have been adding "form-control" classes to my input elements.
But I cannot add the class to your Date Picker (at least I don't think there is a solution to do that in Elm).
Would it be possible to add an option to extend the classList of the Date Picker element?
Thanks!

**Comment by Zimmi48** [comment]
Also, it would be good to be able to parametrize the `style` and `name` attributes.

**Comment by Bogdanp** [comment]
Hi! I've published a new version that will let you set both the input's `classList` and its `name`.

**Comment by Zimmi48** [comment]
That's perfect, thanks!
